<div class="main-content shop-page login-page">

<div class="container">

<h1>TERMINO Y CONDICIONES EMERCATUS</h1>
<hr>
Versión VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR 

Vigente a partir del 27/05/19

Este contrato describe los términos y condiciones generales (los "Términos y Condiciones Generales") aplicables al uso de los servicios ofrecidos por emercatus.cl ("los Servicios") dentro del sitio www.emercatus.cl ("Emercatus" o el "sitio"). Cualquier persona que desee acceder y/o usar el sitio o los servicios podrá hacerlo sujetándose a los Términos y Condiciones Generales, junto con todas las demás políticas y principios que rigen Emercatus y que son incorporados al presente por referencia.

CUALQUIER VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.

El VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de Privacidad así como en los demás documentos incorporados a los mismos por referencia, previo a su inscripción como VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR de Emercatus.cl

Capacidad
Los Servicios sólo están disponibles para personas que tengan capacidad legal para vender y/o exportar. No podrán utilizar los servicios las personas que no tengan tal capacidad, los menores de edad o VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR de Emercatus.cl que hayan sido suspendidos temporalmente o inhabilitados definitivamente. Si estás inscribiendo un VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR como Empresa, debes tener capacidad para contratar a nombre de tal entidad y de obligar a la misma en los términos de este Acuerdo.

Inhabilitación
Cabe comprender que toda inhabilitación se verá realizada por toda falta que conlleve la no cancelación de arriendo del servicio que Emercatus.cl entrega a todo VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR como el romper la transparencia en valores de sus productos exhibidos para evitar el cálculo de tarifas como todo acto que demuestre la rotura de la ética y moral por el cual Emercatus.cl ha sido creado e implementado.

Inscripción
Para poder utilizar los servicios que brinda Emercatus.cl como VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR es obligatorio que todos los campos del formulario de inscripción cuenten con datos válidos. El futuro VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR de Emercatus.cl debe verificar que la información personal o como empresa que pone a disposición de Emercatus.cl a fin de registrarse en el Sitio sea exacta, precisa y verdadera y asume el compromiso de actualizar los Datos Personales conforme resulte necesario. El VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR presta expresa conformidad con que Emercatus utilice diversos medios para identificar sus datos, asumiendo el VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR la obligación de revisarlos y mantenerlos actualizados. Emercatus NO se responsabiliza por la certeza de los Datos del VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR. Los Usuarios garantizan y responden, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de sus Datos Personales.

A su exclusiva discreción, Emercatus podrá requerir una inscripción adicional a los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES que operen como concesionarias o inmobiliarias, como requisito para que dichos Usuarios accedan a paquetes especiales de publicaciones. En estos casos, una vez efectuada la inscripción adicional, las ofertas de venta de automóviles o inmuebles que realicen las concesionarias o inmobiliarias, respectivamente, sólo se publicarán en Emercatus a través de alguno de dichos paquetes o bajo las modalidades que Emercatus habilite para este tipo de VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES.

Emercatus se reserva el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales y/o Empresariales, así como de suspender temporal o definitivamente a aquellos VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES cuyos datos no hayan podido ser confirmados. En estos casos de inhabilitación, se dará de baja todos los artículos publicados, así como las ofertas realizadas, sin que ello genere algún derecho a resarcimiento.

El VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR accederá a su cuenta personal mediante el ingreso de su Seudónimo o de un correo electrónico a su elección, y de la clave de seguridad personal elegida. El Usuario se obliga a mantener la confidencialidad de su Clave de Seguridad. La Cuenta es personal, única e intransferible, y está prohibido que un mismo Usuario inscriba o posea más de una Cuenta. 

El VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR será responsable por todas las operaciones efectuadas en su Cuenta, pues el acceso a la misma está restringido al ingreso y uso de su Clave de Seguridad, de conocimiento exclusivo del VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR. El VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR se compromete a notificar a Emercatus en forma inmediata y por medio idóneo y fehaciente, cualquier uso no autorizado de su Cuenta, así como el ingreso por terceros no autorizados a la misma. Se aclara que está prohibida la venta, cesión o transferencia de la Cuenta (incluyendo la reputación y calificaciones) bajo ningún título.

Emercatus se reserva el derecho de rechazar cualquier solicitud de inscripción o de cancelar una inscripción previamente aceptada, sin que esté obligado a comunicar o exponer las razones de su decisión y sin que ello genere algún derecho a indemnización o resarcimiento.

Modificaciones del Acuerdo
Emercatus podrá modificar los Términos y Condiciones Generales en cualquier momento haciendo públicos en el Sitio los términos modificados. Todos los términos modificados entrarán en vigor a los 10 (diez) días de su publicación. Todo VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR que no esté de acuerdo con las modificaciones efectuadas por Emercatus podrá solicitar la baja de la cuenta.

El uso del sitio y/o sus servicios implica la aceptación de estos Términos y Condiciones generales de uso de Emercatus.

Listado de Bienes
Utilización de Emercatus. Al publicar un anuncio en el Sitio, el VENDEDOR, PROVEEDOR Y/O EXPORTADOR consiente expresamente la utilización de sus propias metodologías para el pago del bien o bienes negociados sin que Emercatus se haga responsable de tal proceso, ya que queda estipulado como de total responsabilidad entre el acuerdo entre Vendedor y Comprador, de la misma forma el proceso de transporte y desplazamiento de los bienes vendidos. Asimismo, el VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR declara que ha leído, comprendido y aceptado los Términos y Condiciones de utilización de dicho servicio.

Publicación de bienes y/o servicios. El VENDEDOR, PROVEEDOR Y/O EXPORTADOR deberá ofrecer a la venta, los bienes en las categorías y subcategorías apropiadas. Las publicaciones podrán incluir textos descriptivos, gráficos, fotografías y otros contenidos y condiciones pertinentes para la venta del bien o la contratación del servicio, siempre que no violen ninguna disposición de este acuerdo o demás políticas de Emercatus. El producto ofrecido por el VENDEDOR, PROVEEDOR Y/O EXPORTADOR debe ser exactamente descrito en cuanto a sus condiciones y características relevantes con la opción de presentar o no el stock disponible con el objetivo de realizar una venta directa y rápida o generar negociación con el comprador potencial. Se entiende y presume que mediante la inclusión del bien, el VENDEDOR, PROVEEDOR Y/O EXPORTADOR acepta que tiene la intención y el derecho de vender el bien por él ofrecido, o está facultado para ello por su titular y lo tiene disponible para su entrega inmediata. Se establece que los precios de los productos publicados deberán ser expresados con IVA incluido cuando corresponda la aplicación del mismo, y en moneda del curso legal. Emercatus podrá remover cualquier publicación cuyo precio no sea expresado de esta forma para evitar confusiones o malos entendidos en cuanto al precio final del producto. Se deja expresamente establecido que ninguna descripción podrá contener datos personales o de contacto, tales como, y sin limitarse a, números telefónicos, dirección de e-mail, dirección postal, direcciones de páginas de Internet que contengan datos como los mencionados anteriormente, ya que el incumplimiento de esta norma conllevará la Inhabilitación de la presente cuenta. En caso que se infrinja cualquiera de las disposiciones establecidas en esta cláusula, Emercatus podrá editar el espacio, solicitar al Usuario que lo edite, o dar de baja la publicación donde se encuentre la infracción.

Inclusión de imágenes y fotografías. El VENDEDOR, PROVEEDOR Y/O EXPORTADOR puede incluir imágenes y fotografías del producto ofrecido siempre que las mismas se correspondan con el artículo, salvo que se trate de bienes o productos o de servicios que por su naturaleza no permiten esa correspondencia. El VENDEDOR, PROVEEDOR Y/O EXPORTADOR declara y garantiza que está facultado para incluir las imágenes y fotografías contenidas en sus publicaciones, siendo responsable por cualquier infracción a derechos de terceros.

Emercatus podrá impedir la publicación de la fotografía, e incluso del producto, si interpretara, a su exclusivo criterio, que la imagen no cumple con los presentes Términos y Condiciones. Las imágenes y fotografías de artículos publicados en el tipo de publicación Clásica, Premium o cualquier categoría que Emercatus cree para el servicio de sus VENDEDORES, PROVEEDORES Y/O EXPORTADORES.

Artículos Prohibidos. Sólo podrán ser ingresados en las listas de bienes ofrecidos, aquellos cuya venta no se encuentre tácita o expresamente prohibida en los Términos y Condiciones Generales y demás políticas de Emercatus o por la ley vigente como la venta de armas, químicos, productos que puedan generar la generación de un mal para la sociedad o cliente.

Protección de Propiedad Intelectual. Emercatus ha desarrollado un Programa (en adelante, "PPPI") destinado a asegurar que los artículos publicados no infringen los derechos de propiedad intelectual e industrial y cualesquiera otros de terceros. Los participantes del PPPI o quienes sean titulares de derechos podrán identificar y solicitar la remoción de aquellos artículos que a su criterio infrinjan o violen sus derechos. En caso que Emercatus sospeche que se está cometiendo o se ha cometido una actividad ilícita o infractora de derechos de propiedad intelectual o industrial, Emercatus se reserva el derecho de adoptar todas las medidas que entienda adecuadas, lo que puede incluir dar acceso limitado a los participantes del PPPI y otros titulares de estos derechos a algunos de sus datos personales.

Privacidad de la Información
Para utilizar los Servicios ofrecidos por Emercatus, los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADOR deberán facilitar determinados datos de carácter personal. Su información personal se procesa y almacena en servidores o medios magnéticos que mantienen altos estándares de seguridad y protección tanto física como tecnológica. 

Obligaciones de los Vendedores, Proveedores y/o Exportadores
Obligaciones del VENDEDOR, PROVEEDOR Y/O EXPORTADOR. Durante el plazo fijado por este, los Compradores interesados realizarán ofertas de compra y/o negociación para los bienes. La oferta de venta se cierra una vez que vence el plazo o se acaban las cantidades estipuladas.

El Comprador y Vendedor recibirán los datos de contacto de ambas partes tras cierre de aprobación de la venta y compra, por el cual podrán coordinar traspaso de bienes monetarios y logística de transporte por el cual Emercatus se excluye en totalidad de tal proceso. 

Al ofertar y/o negociar por un artículo el VENDEDOR, PROVEEDOR Y/O EXPORTADOR acepta quedar obligado por las condiciones de venta incluidas en la descripción del artículo en la medida en que las mismas no infrinjan las leyes o los Términos y Condiciones Generales y demás políticas de Emercatus. La oferta de compra es irrevocable salvo en circunstancias excepcionales, tales como que el VENDEDOR, PROVEEDOR Y/O EXPORTADOR cambie sustancialmente la descripción del artículo después de realizada alguna oferta, que exista un claro error tipográfico, o que no pueda verificar la identidad del VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR.

Los procesos de Venta y Compra solo serán consolidados por el sistema de Emercatus una vez aprobado por ambas partes Vendedor y Comprador el acuerdo del negocio y cerrado trato generando documento oficial de este.

Obligaciones del VENDEDOR, PROVEEDOR Y/O EXPORTADOR. El Vendedor debe tener capacidad legal para vender el bien objeto de su oferta. Si el Usuario Vendedor ha recibido al menos una oferta sobre el precio mínimo que estableció, queda obligado a intentar comunicarse con el comprador y completar la operación con el Usuario que haya realizado la oferta más alta o la que alcance el precio establecido en la modalidad Compra Inmediata. Solamente en casos excepcionales el Vendedor podrá retractarse de la venta, tales como cuando no haya podido acordar con el Usuario Comprador sobre la forma de pago, de entrega o no sea posible verificar la verdadera identidad o demás información del Comprador.

Dado que Emercatus es un punto de encuentro entre comprador y vendedor y no participa de las operaciones que se realizan entre ellos, el Vendedor será responsable por todas las obligaciones y cargas impositivas que correspondan por la venta de sus artículos, sin que pudiera imputársele a Emercatus algún tipo de responsabilidad por incumplimientos en tal sentido.

Emercatus no tiene participación alguna en el proceso de negociación y perfeccionamiento del contrato definitivo entre las partes. Por eso, Emercatus no es responsable por el efectivo cumplimiento de las obligaciones fiscales o impositivas establecidas por la ley vigente.

Obligaciones del Comprador. El Comprador deberá iniciar Negociación y tres este cerrar trato o compra directa expresando en este acto el acuerdo de Venta y Compra, que no signifique esto un falso proceso de este, en caso que el sistema Emercatus detecte un movimiento que signifique fraude, molestias, phishing, o todo acto delictivo podrá optar al cierre y cancelación de la cuenta generadora del problema o falta.
El VENDEDOR, PROVEEDOR Y/O EXPORTADOR acepta que su Comprador puede revocar la compra dentro de un plazo de 5 días hábiles previo a su envío acordado con él Comprador sin afectar el proceso de transporte y logística de este y solo en casos excepcionales en que lo amerite. Asimismo, el VENDEDOR, PROVEEDOR Y/O EXPORTADOR acepta que los compradores podrán pedir el cambio o devolución del producto o los productos tras acuerdo mutuo de negociación entre Vendedor y Comprador, ya que Emercatus solo gestiona el proceso de vitrina de productos para generar negociaciones entre Vendedor y Comprador sin interferir en los acuerdos monetarios y/o transporte de estos.

Prohibiciones
Los VENDEDORES, PROVEEDORES Y/O EXPORTADORES no podrán: (-) interferir en la puja entre distintos VENDEDORES, PROVEEDORES Y/O EXPORTADORES; (-) mantener ningún tipo de comunicación por e-mail, o por cualquier otro medio (incluso redes sociales) durante la oferta del bien con ninguno de los VENDEDORES, PROVEEDORES Y/O EXPORTADORES que participan en la misma; (-) dar a conocer sus datos personales o de otros VENDEDORES, PROVEEDORES Y/O EXPORTADORES a través de la sección de Negociación y/o por algún otro medio (incluyendo pero sin limitar a Twitter, Facebook y/ o cualquier otra red social) a no ser que se haya concretado Negociación pactada entre Vendedor y Comprador, (-) aceptar datos personales proporcionados por otros VENDEDORES, PROVEEDORES Y/O EXPORTADORES a través de la sección de Negociación y/o algún otro medio (incluyendo pero sin limitar Twitter, Facebook y/o cualquier otra red social); (-) publicar o vender artículos prohibidos por los Términos y Condiciones Generales, demás políticas de Emercatus o leyes vigentes; (-) insultar o agredir a otros VENDEDORES, PROVEEDORES Y/O EXPORTADORES; (-) utilizar su reputación, calificaciones o comentarios recibidos en el sitio de Emercatus en cualquier ámbito fuera de este; (-) publicar artículos idénticos en más de una publicación.

Este tipo de actividades será investigado por Emercatus y el infractor podrá ser sancionado con la suspensión o cancelación de la oferta e incluso de su inscripción como Usuario de Emercatus y/o de cualquier otra forma que estime pertinente, sin perjuicio de las acciones legales a que pueda dar lugar por la configuración de delitos o contravenciones o los perjuicios civiles que pueda causar a los VENDEDORES, PROVEEDORES Y/O EXPORTADORES oferentes.

Violaciones del Sistema o Bases de Datos
No está permitida ninguna acción o uso de dispositivo, software, u otro medio tendiente a interferir tanto en las actividades y operatoria de Emercatus como en las ofertas, descripciones, cuentas o bases de datos de Emercatus. Cualquier intromisión, tentativa o actividad violatoria o contraria a las leyes sobre derecho de propiedad intelectual y/o a las prohibiciones estipuladas en este contrato harán pasible a su responsable de las acciones legales pertinentes, y a las sanciones previstas por este acuerdo, así como lo hará responsable de indemnizar los daños ocasionados.

Sanciones. Suspensión de Operaciones
Sin perjuicio de otras medidas, Emercatus podrá advertir, suspender en forma temporal o inhabilitar definitivamente la Cuenta de un VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR o una publicación,  aplicar una sanción que impacte negativamente en la reputación de un VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR, iniciar las acciones que estime pertinentes y/o suspender la prestación de sus Servicios si (-) se quebrantara alguna ley, o cualquiera de las estipulaciones de los Términos y Condiciones Generales y demás políticas de Emercatus; (-) si incumpliera sus compromisos como VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR; (-) si se incurriera a criterio de Emercatus en conductas o actos dolosos o fraudulentos; (-) no pudiera verificarse la identidad del VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR o cualquier información proporcionada por el mismo fuere errónea; (-) Emercatus entendiera que las publicaciones u otras acciones pueden ser causa de responsabilidad para el VENDEDOR, PROVEEDOR Y/O EXPORTADOR que las publicó. En el caso de la suspensión de un VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR, sea temporal o definitiva, todos los artículos que tuviera publicados serán removidos del sistema. También se removerán del sistema las ofertas de compra de bienes ofrecidos.

Responsabilidad
Emercatus sólo pone a disposición de los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES un espacio virtual que les permite ponerse en comunicación mediante Internet para encontrar una forma de vender o comprar bienes. Emercatus no es el propietario de los artículos ofrecidos, no tiene posesión de ellos ni los ofrece en venta. Emercatus no interviene en el perfeccionamiento de las operaciones realizadas entre los VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR ni en las condiciones por ellos estipuladas para las mismas, por ello no será responsable respecto de la existencia, calidad, cantidad, estado, integridad o legitimidad de los bienes ofrecidos, adquiridos o enajenados por los VENDEDORES, PROVEEDORES Y/O EXPORTADORES, así como de la capacidad para contratar de los VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR o de la veracidad de los Datos Personales por ellos ingresados. Cada VENDEDORES, PROVEEDORES Y/O EXPORTADORES conoce y acepta ser el exclusivo responsable por los artículos que publica para su venta y por las ofertas que realiza. 

Debido a que Emercatus no tiene ninguna participación durante todo el tiempo en que el artículo se publica para la venta, ni en la posterior negociación y perfeccionamiento del contrato definitivo entre las partes, no será responsable por el efectivo cumplimiento de las obligaciones asumidas por los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES en el perfeccionamiento de las operaciones. El VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR conoce y acepta que, al realizar operaciones con otros VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES o terceros lo hace bajo su propio riesgo. En ningún caso Emercatus será responsable por lucro cesante, o por cualquier otro daño y/o perjuicio que haya podido sufrir el VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR, debido a las operaciones realizadas o no realizadas por artículos publicados a través de Emercatus.

Emercatus recomienda actuar con prudencia y sentido común al momento de realizar operaciones con otros VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES. El VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR debe tener presente, además, los riesgos de contratar con menores o con personas que se valgan de una identidad falsa. Emercatus “NO” será responsable por la realización de ofertas y/o operaciones con otros VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADOR basadas en la confianza depositada en el sistema o los Servicios brindados por Emercatus.

En caso que uno o más VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES o algún tercero inicien cualquier tipo de reclamo o acciones legales contra otro u otros VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES, todos y cada uno de los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES involucrados en dichos reclamos o acciones eximen de toda responsabilidad a Emercatus y a sus directores, gerentes, empleados, agentes, operarios, representantes y apoderados. 

Alcance de los servicios de Emercatus
Este acuerdo no crea ningún contrato de sociedad, de mandato, de franquicia, o relación laboral entre Emercatus y el VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR. El VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR reconoce y acepta que Emercatus no es parte en ninguna operación, ni tiene control alguno sobre la calidad, seguridad o legalidad de los artículos anunciados, la veracidad o exactitud de los anuncios, la capacidad de los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES para vender o comprar artículos. Emercatus no puede asegurar que un VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR completará una operación ni podrá verificar la identidad o Datos Personales ingresado. Emercatus no garantiza la veracidad de la publicidad de terceros que aparezca en el sitio y no será responsable por la correspondencia o contratos que el Usuario celebre con dichos terceros o con otros VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES.

Fallas en el sistema
Emercatus no se responsabiliza por cualquier daño, perjuicio o pérdida al VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR causados por fallas en el sistema, en el servidor o en Internet. Emercatus tampoco será responsable por cualquier virus que pudiera infectar el equipo del VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR como consecuencia del acceso, uso o examen de su sitio web o a raíz de cualquier transferencia de datos, archivos, imágenes, textos, o audio contenidos en el mismo. Los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES “NO” podrán imputarle responsabilidad alguna ni exigir pago por lucro cesante, en virtud de perjuicios resultantes de dificultades técnicas o fallas en los sistemas o en Internet. Emercatus no garantiza el acceso y uso continuado o ininterrumpido de su sitio. El sistema puede eventualmente no estar disponible debido a dificultades técnicas o fallas de Internet, o por cualquier otra circunstancia ajena a Emercatus; en tales casos se procurará restablecerlo con la mayor celeridad posible sin que por ello pueda imputársele algún tipo de responsabilidad. Emercatus no será responsable por ningún error u omisión contenidos en su sitio web.

Tarifas y/o Facturación
Las Tarifas ….

Sistema de Reputación y Reportabilidad
Debido a que la verificación de la identidad de los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES en Internet es difícil, Emercatus no puede confirmar ni confirma la identidad pretendida de cada VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR. Por ello el VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR cuenta con un sistema de reputación de VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR que es actualizado periódicamente en base a datos vinculados con su actividad en el sitio y a los comentarios ingresados por los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES según las operaciones que hayan realizado. De misma forma Emercatus tendrá la facultad de generar Reportes, Indicadores, Estadísticas y Estudios en base de todos los procesos que se ejecuten dentro de la Plataforma, esto podrá ser implementado, ejecutado o publicado en períodos que Emercatus estime conveniente y su uso necesario.

En virtud que las calificaciones y comentarios que son realizados por los VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES, éstos serán incluidos bajo exclusiva responsabilidad de quienes los emitan. Emercatus “NO” tiene obligación de verificar la veracidad o exactitud de los mismos y “NO” se responsabiliza por los dichos allí vertidos por cualquier Proveedor o Comprador.

Propiedad intelectual. Enlaces
Los contenidos de las pantallas relativas a los servicios de Emercatus como así también los programas, bases de datos, redes, archivos que permiten al Usuario acceder y usar su Cuenta, son de propiedad de Emercatus y están protegidas por las leyes y los tratados internacionales de derecho de autor, marcas, patentes, modelos y diseños industriales. El uso indebido y la reproducción total o parcial de dichos contenidos quedan prohibidos, salvo autorización expresa y por escrito de Emercatus. 
 
El Sitio puede contener enlaces a otros sitios web lo cual no indica que sean propiedad u operados por Emercatus. En virtud que Emercatus no tiene control sobre tales sitios, “NO” será responsable por los contenidos, materiales, acciones y/o servicios prestados por los mismos, ni por daños o pérdidas ocasionadas por la utilización de los mismos, sean causadas directa o indirectamente. La presencia de enlaces a otros sitios web no implica una sociedad, relación, aprobación, respaldo de Emercatus a dichos sitios y sus contenidos.
Indemnidad
El VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR mantendrá indemne a Emercatus, así como a sus filiales, empresas controladas y/o controlantes, funcionarios, directivos, sucesores, administradores, representantes y empleados, por cualquier reclamo iniciado por otros VENDEDORES, PROVEEDORES Y/O EXPORTADORES o en caso contrario COMPRADORES, terceros o por cualquier Organismo, relacionado con sus actividades en el Sitio, el cumplimiento y/o el incumplimiento de los Términos y Condiciones Generales o demás Políticas, así como respecto de cualquier violación de leyes o derechos de terceros.
A tal fin, el VENDEDOR, PROVEEDOR Y/O EXPORTADOR o en caso contrario COMPRADOR faculta a Emercatus a: i) intervenir y representarlo en dichos reclamos, pudiendo celebrar los acuerdos transaccionales que considere oportunos y que tiendan a evitar mayores costos y/o evitar eventuales contingencias sin limitación, en su nombre y representación; ii) retener y debitar de su Cuenta de Emercatus los fondos existentes y/o futuros para recuperar los gastos incurridos en los acuerdos, los cuales podrán incluir los honorarios de los letrados intervinientes y las costas judiciales en una cantidad razonable, y/o iii) generar débitos específicos en su facturación.

Jurisdicción y Ley Aplicable
Este acuerdo estará regido en todos sus puntos por las leyes vigentes en la República Chilena.

Cualquier controversia derivada del presente acuerdo, su existencia, validez, interpretación, alcance o cumplimiento, será sometida a las leyes aplicables y a los Tribunales competentes de la Ciudad de Santiago y los procedimientos se llevarán a cabo en idioma castellano.

Atentamente Equipo Gerencial Plataforma EMERCATUS.CL

		



</div>
</div>